Repository bitcoin-core/gui, pull requests merged in 2021-06, with the labels that each got.

#123 rpc: Do not accept command while executing another one
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
  src/qt/test/apptests.cpp
Labels: Feature

#351 Translations update
  src/qt/locale/bitcoin_en.ts
  src/qt/locale/bitcoin_en.xlf
Labels: Translations

#325 Align numbers in the "Peer Id" column to the right
  src/qt/peertablemodel.cpp
  src/qt/rpcconsole.cpp
Labels: UI

#329 Make console buttons look clickable
  src/qt/forms/debugwindow.ui
  src/qt/rpcconsole.cpp
Labels: UI

#256 Save/restore column sizes of the tables in the Peers tab
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
Labels: Feature

#29 refactor: Optimize signal-slot connections logic
  src/qt/bitcoingui.cpp
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring

#164 Handle peer addition/removal in a right way
  src/qt/peertablemodel.cpp
  src/qt/peertablemodel.h
  src/qt/rpcconsole.cpp
Labels: Bug

#4 UI external signer support (e.g. hardware wallet)
  src/interfaces/node.h
  src/interfaces/wallet.h
  src/node/interfaces.cpp
  src/qt/createwalletdialog.cpp
  src/qt/createwalletdialog.h
  src/qt/forms/createwalletdialog.ui
  src/qt/forms/optionsdialog.ui
  src/qt/forms/receiverequestdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/receiverequestdialog.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/walletcontroller.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/walletmodeltransaction.cpp
  src/qt/walletmodeltransaction.h
  src/wallet/interfaces.cpp
Labels: Feature, Wallet

#361 Fix gui segfault caused by bitcoin/bitcoin#22216
  src/qt/bitcoin.cpp
Labels: Bug, Wallet

#333 refactor: Signal-slot connections cleanup
  src/qt/bitcoingui.cpp
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletview.cpp
  src/qt/walletview.h
Labels: Refactoring, Wallet

#362 Add keyboard shortcuts to context menus
  src/qt/addressbookpage.cpp
  src/qt/coincontroldialog.cpp
  src/qt/qrimagewidget.cpp
  src/qt/receivecoinsdialog.cpp
  src/qt/rpcconsole.cpp
  src/qt/transactionview.cpp
Labels: Bug, UI
