Repository bitcoin-core/gui, pull requests merged in 2021-08, with the labels that each got.

#337 test: Use Regex Search in Apptests
  src/qt/test/apptests.cpp
Labels: Tests

#393 Fix regression in "Encrypt Wallet" menu item
  src/qt/bitcoingui.cpp
Labels: Bug, Needs backport (22.x), UX, Wallet

#379 Prompt to reset settings when settings.json cannot be read
  src/qt/bitcoin.cpp
Labels: UX

#396 Ensure external signer option remains disabled without signers
  src/qt/createwalletdialog.cpp
  src/qt/createwalletdialog.h
Labels: Bug, Wallet, Needs backport (22.x)

#354 Refactor open date range to use std::optional
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionfilterproxy.h
  src/qt/transactionview.cpp
Labels: Refactoring

#399 Fix "Load PSBT" functionality when no wallet loaded
  src/qt/bitcoingui.cpp
  src/qt/psbtoperationsdialog.cpp
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletview.cpp
  src/qt/walletview.h
Labels: Bug, Wallet, UX

#390 Add SubFeeFromAmount to options
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/sendcoinsentry.cpp
Labels: Wallet, UX

#406 Handle new added plurals in bitcoin_en.ts
  src/qt/locale/bitcoin_en.ts
Labels: Translations, Needs backport (22.x)

#408 Add missing mnemonics in menu bar options
  src/qt/bitcoingui.cpp
Labels: UX

#349 replace QDateTime::fromTime_t with QDateTime::fromSecsSinceEpoch
  src/qt/bitcoingui.cpp
  src/qt/clientmodel.cpp
  src/qt/guiutil.cpp
  src/qt/recentrequeststablemodel.cpp
  src/qt/recentrequeststablemodel.h
  src/qt/rpcconsole.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactiontablemodel.cpp
Labels: Refactoring
