Repository bitcoin-core/gui, pull requests merged in 2021-07, with the labels that each got.

#366 Dark Mode fixes/portability
  src/qt/bitcoingui.cpp
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/overviewpage.cpp
  src/qt/rpcconsole.cpp
  src/qt/sendcoinsentry.cpp
  src/qt/signverifymessagedialog.cpp
  src/qt/transactionview.cpp
Labels: UI

#330 Allow prompt icon to be colorized
  src/qt/rpcconsole.cpp
Labels: UI

#377 Translations update
  src/qt/bitcoinstrings.cpp
  src/qt/locale/bitcoin_en.ts
  src/qt/locale/bitcoin_en.xlf
Labels: Translations

#365 Draw "eye" sign at the beginning of watch-only addresses
  src/qt/overviewpage.cpp
Labels: Bug, UI, needs backport (0.21)

#375 Emit dataChanged signal to dynamically re-sort Peers table
  src/qt/peertablemodel.cpp
  src/qt/peertablemodel.h
  src/qt/rpcconsole.cpp
Labels: Bug, UI

#381 refactor: Make BitcoinCore class reusable
  build_msvc/libbitcoin_qt/libbitcoin_qt.vcxproj
  src/Makefile.qt.include
  src/qt/bitcoin.cpp
  src/qt/bitcoin.h
  src/qt/initexecutor.cpp
  src/qt/initexecutor.h
  src/qt/test/test_main.cpp
Labels: Refactoring
