Repository bitcoin-core/gui, pull requests merged in 2021-09, with the labels that each got.

#398 refactor: Pass WalletModel object to the WalletView constructor
  src/qt/bitcoingui.cpp
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletview.cpp
  src/qt/walletview.h
Labels: Refactoring, Wallet

#318 Add `Copy address` Peers Tab Context Menu Action
  src/qt/rpcconsole.cpp
Labels: UX

#391 Add cancel button to configuration options popup
  src/qt/optionsdialog.cpp
Labels: UX

#419 Add missing tooltips to options menu settings
  src/qt/forms/optionsdialog.ui
Labels: Doc, UI

#418 fix bitcoin-qt app categorization on apple silicon
  share/qt/Info.plist.in
Labels: Bug, macOS

#420 Ensure translator comments end in full stop
  src/qt/addressbookpage.cpp
  src/qt/qrimagewidget.cpp
  src/qt/rpcconsole.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/transactionview.cpp
Labels: Translations

#434 Keep InitExecutor in main gui thread
  src/qt/initexecutor.cpp
  src/qt/initexecutor.h
  src/qt/test/test_main.cpp
Labels: Refactoring

#345 Connection Type Translator Comments
  src/qt/guiutil.cpp
  src/qt/rpcconsole.cpp
Labels: Translations

#416 Add RPC setting
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
Labels: Feature, Needs release notes, UX

#430 Improvements to the open up transaction in third-party link action
  src/qt/forms/optionsdialog.ui
  src/qt/transactionview.cpp
Labels: UI

#436 Include vout when copying transaction ID from coin selection
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
Labels: Wallet

#439 Do not show unused widgets at startup
  src/qt/bitcoingui.cpp
Labels: UI

#336 Do not exit and re-enter main event loop during shutdown
  src/qt/addressbookpage.cpp
  src/qt/bitcoin.cpp
  src/qt/bitcoin.h
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
  src/qt/sendcoinsdialog.cpp
  src/qt/transactionview.cpp
  src/qt/walletframe.cpp
  src/qt/walletmodel.cpp
  src/qt/walletview.cpp
Labels: Refactoring

#342 wallet: Move wallets loading out from the main GUI thread
  src/qt/bitcoingui.cpp
  src/qt/walletcontroller.cpp
  src/qt/walletcontroller.h
Labels: Wallet, UX
