Repository bitcoin-core/gui, pull requests merged in 2021-11, with the labels that each got.

#449 Restore "S" accelerator for "Start on system login" option
  src/qt/forms/optionsdialog.ui
Labels: UX

#319 Paste button in Open URI dialog
  src/qt/bitcoingui.cpp
  src/qt/forms/openuridialog.ui
  src/qt/openuridialog.cpp
  src/qt/openuridialog.h
Labels: UX, UI

#477 Monospaced output in Console on macOS
  src/qt/rpcconsole.cpp
Labels: macOS, UI
