Repository bitcoin-core/gui, pull requests merged in 2021-04, with the labels that each got.

#266 Doc: Copyright: Fix embedded font file location
  contrib/debian/copyright
Labels: Doc

#260 Handle exceptions instead of crash
  src/qt/bitcoin.cpp
  src/qt/bitcoin.h
  src/qt/bitcoingui.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
  src/qt/test/wallettests.cpp
  src/qt/transactionview.cpp
  src/qt/transactionview.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Bug

#277 Do not use QClipboard::Selection on Windows and macOS.
  src/qt/guiutil.cpp
Labels: Bug, macOS, windows

#276 Elide long strings in their middle in the Peers tab
  src/qt/forms/debugwindow.ui
Labels: Design, Feature

#263 Revamp context menus
  src/qt/addressbookpage.cpp
  src/qt/addressbookpage.h
  src/qt/bitcoingui.cpp
  src/qt/coincontroldialog.cpp
  src/qt/qrimagewidget.cpp
  src/qt/receivecoinsdialog.cpp
  src/qt/rpcconsole.cpp
  src/qt/transactionview.cpp
Labels: Refactoring

#286 qt: Bump transifex slug for 22.x
  .tx/config
Labels: Translations

#284 refactor: Simplify SendCoinsDialog::updateCoinControlState
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
Labels: Refactoring, Wallet

#18 Add peertablesortproxy module
  build_msvc/libbitcoin_qt/libbitcoin_qt.vcxproj
  src/Makefile.qt.include
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/peertablemodel.cpp
  src/qt/peertablemodel.h
  src/qt/peertablesortproxy.cpp
  src/qt/peertablesortproxy.h
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
Labels: Bug

#125 Enable changing the autoprune block space size in intro dialog
  src/qt/bitcoin.cpp
  src/qt/bitcoin.h
  src/qt/forms/intro.ui
  src/qt/intro.cpp
  src/qt/intro.h
Labels: Feature

#300 Remove progress bar on modal overlay
  src/qt/forms/modaloverlay.ui
  src/qt/modaloverlay.cpp
Labels: Design

#298 Peertableview alternating row colors
  src/qt/forms/debugwindow.ui
Labels: Design
