Repository bitcoin-core/gui, pull requests merged in 2021-03, with the labels that each got.

#166 refactor: Use enum type as switch argument in *TableModel
  src/qt/addresstablemodel.cpp
  src/qt/bantablemodel.cpp
  src/qt/peertablemodel.cpp
  src/qt/transactiontablemodel.cpp
Labels: Refactoring

#233 qt test: Don't bind to regtest port
  src/qt/test/test_main.cpp
Labels: Tests

#229 Fix regression with initial sorting after pr205
  src/qt/receivecoinsdialog.cpp
  src/qt/transactionview.cpp
Labels: Bug

#188 Write PSBTs to file with binary mode
  src/qt/psbtoperationsdialog.cpp
  src/qt/sendcoinsdialog.cpp
Labels: windows

#250 scripted-diff: Drop redundant QString calls
  src/qt/guiutil.cpp
Labels: Refactoring

#246 Revert "qt: Use "fusion" style on macOS Big Sur with old Qt"
  src/qt/bitcoin.cpp
Labels: macOS

#248 Fix: For values of "Bytes transferred" and "Bytes/s" with 1000-based prefix names use 1000-based divisor instead of 1024-based
  src/qt/guiutil.cpp
  src/qt/trafficgraphwidget.cpp
Labels: Feature

#243 fix issue when disabling the auto-enabled blank wallet checkbox
  src/qt/createwalletdialog.cpp
Labels: Design

#254 refactor: Drop redundant setEditTriggers(NoEditTriggers) calls
  src/qt/rpcconsole.cpp
Labels: Refactoring

#251 Improve URI/file handling message
  src/qt/paymentserver.cpp
Labels: Doc

#154 qt: Support macOS Dark mode
  doc/release-notes.md
  share/qt/Info.plist.in
  src/qt/platformstyle.cpp
Labels: macOS
