Repository bitcoin-core/gui, pull requests merged in 2021-05, with the labels that each got.

#296 Do not use QObject::tr plural syntax for numbers with a unit symbol
  src/qt/intro.cpp
Labels: Translations

#257 refactor: Use template function qOverload in signal-slot connections
  src/qt/bitcoinamountfield.cpp
  src/qt/bitcoingui.cpp
  src/qt/intro.cpp
  src/qt/optionsdialog.cpp
  src/qt/qvaluecombobox.cpp
  src/qt/rpcconsole.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/transactionview.cpp
  src/qt/walletview.cpp
Labels: Refactoring

#194 Save/restore RPCConsole geometry only for window
  src/qt/rpcconsole.cpp
Labels: Feature

#280 Remove user input from URI error message
  src/qt/paymentserver.cpp
Labels: Feature, needs backport (0.21)

#271 Don't clear console prompt when font resizing
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
Labels: UX

#323 English translations update
  share/qt/extract_strings_qt.py
  src/qt/bitcoinstrings.cpp
  src/qt/locale/bitcoin_en.ts
  src/qt/locale/bitcoin_en.xlf
Labels: Translations

#281 set shortcuts for console's resize buttons
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/rpcconsole.cpp
Labels: UX

#335 test: Use QSignalSpy instead of QEventLoop
  src/qt/test/apptests.cpp
Labels: Tests

#297 Avoid unnecessary translations
  src/qt/forms/optionsdialog.ui
Labels: Translations

#121 Early subscribe core signals in transaction table model
  src/qt/transactiontablemodel.cpp
Labels: Bug, Wallet

#313 qt: Optimize string concatenation by default
  src/Makefile.qt.include
  src/qt/bitcoin.cpp
  src/qt/guiutil.cpp
  src/qt/optionsmodel.cpp
  src/qt/peertablemodel.cpp
  src/qt/recentrequeststablemodel.cpp
  src/qt/test/wallettests.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactiontablemodel.cpp
Labels: Refactoring

#311 Peers Window rename 'Peer id' to 'Peer'
  src/qt/peertablemodel.h
  src/qt/rpcconsole.cpp
Labels: Translations, UI

#332 Replace disambiguation strings with translator comments
  src/qt/addressbookpage.cpp
  src/qt/intro.cpp
  src/qt/psbtoperationsdialog.cpp
  src/qt/qrimagewidget.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/transactionview.cpp
  src/qt/walletview.cpp
Labels: Translations

#275 Support runtime appearance adjustment on macOS
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/platformstyle.cpp
  src/qt/platformstyle.h
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
  src/qt/sendcoinsentry.cpp
  src/qt/sendcoinsentry.h
  src/qt/signverifymessagedialog.cpp
  src/qt/signverifymessagedialog.h
  src/qt/transactionview.cpp
  src/qt/transactionview.h
Labels: macOS

#343 Improve the GUI responsiveness when progress dialogs are used
  src/qt/bitcoingui.cpp
  src/qt/guiutil.cpp
  src/qt/walletcontroller.cpp
  src/qt/walletview.cpp
Labels: UX, Wallet

#309 Add access to the Peers tab from the network icon
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
Labels: Feature, UX

#331 Make RPC console welcome message translation-friendly
  src/qt/rpcconsole.cpp
Labels: Translations
