Repository bitcoin-core/gui, pull requests merged in 2021-12, with the labels that each got.

#493 qt: Handle Android back key in the Node window
  src/qt/guiutil.h
  src/qt/rpcconsole.cpp
Labels: UX, Android

#508 Prevent negative values of progressPerHour
  src/qt/modaloverlay.cpp
Labels: UX

#459 Address type dropdown, add Taproot (Receive tab)
  doc/release-notes-gui-459.md
  src/interfaces/wallet.h
  src/qt/forms/receivecoinsdialog.ui
  src/qt/receivecoinsdialog.cpp
  src/wallet/interfaces.cpp
Labels: Feature, Wallet, UX
