Repository bitcoin-core/gui, pull requests merged in 2022-02, with the labels that each got.

#524 Replace int with std::chrono in for the timer->setInterval() argument
  src/qt/rpcconsole.cpp
  src/qt/trafficgraphwidget.cpp
  src/qt/trafficgraphwidget.h
Labels: Refactoring

#404 Fix various edge case bugs in QValidatedLineEdit
  src/qt/qvalidatedlineedit.cpp
  src/qt/qvalidatedlineedit.h
Labels: Bug

#509 Respect dialog modality and fix a regression in wallet unlock
  src/qt/addressbookpage.cpp
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/sendcoinsdialog.cpp
  src/qt/transactionview.cpp
  src/qt/walletframe.cpp
  src/qt/walletview.cpp
Labels: Bug, Wallet

#547 Override BitcoinApplication::event() to handle QEvent::Quit
  src/qt/bitcoin.cpp
  src/qt/bitcoin.h
Labels: Bug, UX
