Repository bitcoin-core/gui, pull requests merged in 2022-04, with the labels that each got.

#543 peers-tab: add connection duration column to tableview
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/peertablemodel.cpp
  src/qt/peertablemodel.h
  src/qt/peertablesortproxy.cpp
  src/qt/rpcconsole.cpp
Labels: Feature

#576 Add qt unit test runner summary
  src/qt/test/test_main.cpp
Labels: Tests

#577 Getting ready to Qt 6 (1/n)
  src/qt/bitcoingui.cpp
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/walletview.cpp
Labels: Qt 6

#552 Refactor `TransactionDesc::FormatTxStatus` and ` TransactionStatus`
  src/qt/transactiondesc.cpp
  src/qt/transactiondesc.h
  src/qt/transactionrecord.h
Labels: Refactoring

#556 refactor: Make BitcoinUnits::Unit a scoped enum
  src/qt/bitcoin.cpp
  src/qt/bitcoinamountfield.cpp
  src/qt/bitcoinamountfield.h
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/bitcoinunits.cpp
  src/qt/bitcoinunits.h
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/overviewpage.cpp
  src/qt/psbtoperationsdialog.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/test/wallettests.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactiondesc.h
  src/qt/transactiontablemodel.cpp
  src/qt/walletview.h
Labels: Refactoring

#579 Getting ready to Qt 6 (2/n). Remove `QApplication::globalStrut()`
  src/qt/bitcoinamountfield.cpp
Labels: Qt 6

#580 Getting ready to Qt 6 (3/n). Do not use `QKeyEvent` copy constructor
  src/qt/rpcconsole.cpp
Labels: Qt 6

#584 Getting ready to Qt 6 (5/n). Do not assume `qDBusRegisterMetaType` return type
  src/qt/notificator.cpp
Labels: Qt 6

#587 refactor: Replace `GUIUtil::ObjectInvoke()` with `QMetaObject::invokeMethod()`
  src/qt/guiutil.h
  src/qt/initexecutor.cpp
  src/qt/walletcontroller.cpp
Labels: Refactoring
