Repository bitcoin-core/gui, pull requests merged in 2022-12, with the labels that each got.

#683 doc: Drop no longer relevant comment
  src/qt/test/test_main.cpp
Labels: Doc

#682 Don't directly delete abandoned txes from GUI
  src/qt/transactionview.cpp
Labels: Wallet

#605 Delete splash screen widget early
  src/qt/bitcoin.cpp
  src/qt/bitcoin.h
  src/qt/splashscreen.cpp
  src/qt/splashscreen.h
Labels: Bug, Wallet

#687 Load PSBTs using istreambuf_iterator rather than istream_iterator
  src/qt/walletframe.cpp
Labels: Wallet, Needs backport (24.x)
