Repository bitcoin-core/gui, pull requests merged in 2022-03, with the labels that each got.

#549 refactor: use std::chrono for formatDurationStr() helper
  src/qt/guiutil.cpp
Labels: Refactoring

#555 Restore Send button when using external signer
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
Labels: Wallet, UX, Needs backport (23.x)

#554 Add and improve translator comments and tooltips for peers tab address fields
  src/qt/forms/debugwindow.ui
Labels: Translations

#568 options: flip listenonion to false if not listening
  src/qt/optionsmodel.cpp
Labels: UX, Needs backport (23.x)
