Repository bitcoin-core/gui, pull requests merged in 2022-06, with the labels that each got.

#613 Remove unnecessary wallet includes from rpcconsole.cpp
  src/qt/rpcconsole.cpp
Labels: Wallet

#583 Add translator comments to `TransactionDesc::FormatTxStatus`
  src/qt/transactiondesc.cpp
Labels: Translations

#608 wallet, refactor: Make `WalletModel::sendCoins()` return `void`
  src/qt/sendcoinsdialog.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Refactoring, Wallet

#615 If -prune=0 is set, Uncheck Prune on Intro page
  src/qt/intro.cpp
Labels: UX

#612 refactor: Drop unused `QFrame`s in `SendCoinsEntry`
  src/qt/forms/sendcoinsentry.ui
  src/qt/sendcoinsentry.cpp
  src/qt/sendcoinsentry.h
Labels: Refactoring, UI

#620 Replace `QRegExp` with `QRegularExpression`
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/test/optiontests.cpp
  src/qt/test/optiontests.h
  src/qt/utilitydialog.cpp
Labels: Refactoring, Qt 6

#623 Getting ready to Qt 6 (9/n). Apply Qt 6 specific changes
  src/qt/bitcoin.cpp
Labels: Qt 6

#617 Reset options, notify user about backup creation
  src/qt/bitcoingui.cpp
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
Labels: UX
