Repository bitcoin-core/gui, pull requests merged in 2022-01, with the labels that each got.

#441 Add Create Unsigned button to SendConfirmationDialog
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
  src/qt/walletmodel.cpp
Labels: UX

#523 scripted-diff: Rename functions to drop mention of boost
  src/qt/clientmodel.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/intro.cpp
  src/qt/optionsmodel.cpp
  src/qt/paymentserver.cpp
Labels: Refactoring

#517 refactor, qt: Use std::chrono for parameters of QTimer methods
  src/qt/bitcoin.cpp
  src/qt/clientmodel.cpp
  src/qt/guiconstants.h
  src/qt/optionsdialog.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/test/addressbooktests.cpp
  src/qt/test/util.cpp
  src/qt/test/util.h
  src/qt/test/wallettests.cpp
  src/qt/transactionview.cpp
  src/qt/walletcontroller.cpp
Labels: Refactoring

#526 Add address relay/processed/rate-limited fields to peer details
  src/qt/forms/debugwindow.ui
  src/qt/rpcconsole.cpp
Labels: Feature
