Repository bitcoin-core/gui, pull requests merged in 2022-05, with the labels that each got.

#591 test: Add tests for `tableView` in `AddressBookPage` dialog
  src/qt/test/addressbooktests.cpp
  src/qt/walletmodel.cpp
Labels: Tests

#590 refactor: Declare `WalletModel` member functions with `const`
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Refactoring, Wallet

#594 scripted-diff: replace deprecated Q_OS_MAC with Q_OS_MACOS
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/guiutil.cpp
  src/qt/notificator.cpp
  src/qt/notificator.h
  src/qt/optionsdialog.cpp
  src/qt/rpcconsole.cpp
  src/qt/test/addressbooktests.cpp
  src/qt/test/apptests.cpp
  src/qt/test/wallettests.cpp
Labels: macOS

#581 refactor: Revamp `ClientModel` code to handle core signals
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
Labels: Refactoring

#600 refactor: Add OptionsModel getOption/setOption methods
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
Labels: Refactoring

#586 Getting ready to Qt 6 (6/n). Replace `QCoreApplication::quit()` with `QCoreApplication::exit(0)`
  src/qt/bitcoin.cpp
  src/qt/test/apptests.cpp
Labels: Qt 6

#601 refactor: Pass interfaces::Node references to OptionsModel constructor
  src/qt/bitcoin.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/test/addressbooktests.cpp
  src/qt/test/optiontests.cpp
  src/qt/test/optiontests.h
  src/qt/test/wallettests.cpp
Labels: Refactoring

#609 wallet, refactor: Drop unused `WalletModel::PaymentRequestExpired`
  src/qt/sendcoinsdialog.cpp
  src/qt/walletmodel.h
Labels: Refactoring, Wallet
