Repository bitcoin-core/gui, pull requests merged in 2023-10, with the labels that each got.

#757 Add wallet name to address book page title
  src/qt/addressbookpage.cpp
  src/qt/addressbookpage.h
  src/qt/addresstablemodel.cpp
  src/qt/addresstablemodel.h
Labels: Wallet, UX

#764 Remove legacy wallet creation
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/createwalletdialog.cpp
  src/qt/createwalletdialog.h
  src/qt/forms/createwalletdialog.ui
  src/qt/walletcontroller.cpp
Labels: Wallet

#767 Update translation source file for v26.0 string freeze
  src/qt/bitcoinstrings.cpp
  src/qt/locale/bitcoin_en.ts
  src/qt/locale/bitcoin_en.xlf
Labels: Translations

#742 Exit and show error if unrecognized command line args are present
  src/qt/bitcoin.cpp
  src/qt/paymentserver.h
Labels: CI failed

#771 Avoid error-prone leading whitespace in translatable strings
  src/qt/psbtoperationsdialog.cpp
  src/qt/psbtoperationsdialog.h
  src/qt/sendcoinsdialog.cpp
  src/qt/transactiondesc.cpp
  src/qt/walletcontroller.cpp
  test/lint/lint-qt-translation.py
Labels: Tests, Translations
