Repository bitcoin-core/gui, pull requests merged in 2023-02, with the labels that each got.

#704 Correctly limit overview transaction list
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionfilterproxy.h
Labels: Bug, UI, Needs backport (24.x)

#705 doc: Fix comment about how wallet txs are sorted
  src/qt/transactiontablemodel.cpp
Labels: Doc, Wallet

#653 Show watchonly balance only for Legacy wallets
  src/qt/sendcoinsdialog.cpp
Labels: Wallet, UX

#697 Remove reindex special case from the progress bar label
  src/interfaces/node.h
  src/node/interfaces.cpp
  src/qt/bitcoingui.cpp
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
Labels: UI

#701 Persist Mask Values option
  src/qt/bitcoingui.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/overviewpage.cpp
Labels: Feature, UX

#603 Add settings.json prune-prev, proxy-prev, onion-prev settings
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
Labels: UX

#711 refactor: Disable unused special members functions in `UnlockContext`
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Wallet
