Repository bitcoin-core/gui, pull requests merged in 2024-02, with the labels that each got.

#553 Change address / amount error background
  src/qt/guiconstants.h
Labels: UI, CI failed

#497 Enable users to configure their monospace font specifically
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
Labels: Feature, UX, CI failed

#780 Fix: Ensure 'Transaction View' remains disabled if no wallet is selected
  src/qt/bitcoingui.cpp
Labels: CI failed

#658 Intro: Never change the prune checkbox after the user has touched it
  src/qt/intro.cpp
  src/qt/intro.h
Labels: UX, CI failed

#758 Update Node window title with the chain type
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
Labels: CI failed

#773 Check for private keys disabled before attempting unlock
  src/qt/walletmodel.cpp
Labels: Wallet, CI failed

#797 test: Recognize dialog object by name
  src/qt/sendcoinsdialog.cpp
  src/qt/test/wallettests.cpp
Labels: Tests
